name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 3:55 am
    - cron: '55 3 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://habr.com/ru/rss/hubs/javascript/articles/rated10/?fl=ru"         
